Add links to CCG from S2S guides
ngrok/ngrok-docs pull request #1010
Opened 2024-10-28 15:35 UTC by joelhans

Following up on #1008 by adding a few cross-links from existing guides.

Very much open to feedback on the copy itself or its positioning within the S2S guides.

2024-10-29 16:22 UTC, DevMandy requested changes

2024-10-29 16:22 UTC, DevMandy commented on docs/faq/faq.md
>  traffic to those endpoints, but ngrok provides a [number of mechanisms](https://ngrok.com/docs/guides/security-dev-productivity/) to control
traffic to those endpoints, but ngrok provides a [number of mechanisms](/docs/other-guides/security-dev-productivity/) to control

2024-10-29 16:22 UTC, DevMandy commented on docs/faq/faq.md
>  traffic to those endpoints, but ngrok provides a [number of mechanisms](https://ngrok.com/docs/guides/security-dev-productivity/) to control
Update the link

2024-10-29 16:22 UTC, DevMandy commented on docs/faq/faq.md
> +with your vendor to implement adequate security practices, see our [end customer installation guide](end-customers.mdx).
with your vendor to implement adequate security practices, see our [end customer installation guide](/docs/guides/site-to-site-connectivity/end-customers/).

2024-10-29 18:20 UTC, joelhans commented
@DevMandy Fixed both of those. TYVM!

2024-11-04 20:01 UTC, DevMandy approved these changes

2024-11-04 20:05 UTC, merged