[WIP] Rewrite Quickstart to use Traffic Policy
ngrok/ngrok-docs pull request #1050
Opened 2024-11-27 21:12 UTC by joelhans

Been thinking about the quickstart a lot lately—wanted to take a stab at rewriting this to direct folks toward Traffic Policy and follow the general movement from tunnels->agent endpoints, etc.

Still a draft because I have to figure out a few big thing still:

- [ ] Figure out a few basic concepts of Traffic Policy (phases, rules) to introduce and in what manner without overwhelming users
- [ ] Possibly add another action or two—what examples are easiest to implement *and* most illustrative in their value or flexibility?
- [ ] Change links in the **What's next** section to point toward newer resources like Traffic Policy

I think this holds us over for a *bit*, but we'll also want to start considering the implications of new things like creating cloud endpoints in the UI, cloud+internal setups, etc. Also, #1011 will have some big implications on how we introduce Traffic Policy.

*VERY* open to feedback in this early ideation.

2024-12-10 05:53 UTC, russorat commented on docs/getting-started/index.mdx
> +<ol className="marker:text-xl marker:font-bold marker:text-blue-500 pl-8">
this layout looks a little strange to me. can we use something more simple like in https://ngrok.com/docs/traffic-policy/getting-started/#prerequisites ?
<img width="933" alt="image" src="https://github.com/user-attachments/assets/c7f502e6-04e2-40a9-aa08-a8f7b16bf3da">

2024-12-10 05:53 UTC, russorat commented on docs/getting-started/index.mdx
> +<p className="text-lg">
i don't think this needs to be in large text. normal size is ok.

2024-12-10 05:56 UTC, russorat commented on docs/getting-started/index.mdx
> +ngrok http 8080
earlier, we told them to have something running on port 8000, now we are using port 8080. might cause confusion.

2024-12-10 05:57 UTC, russorat commented on docs/getting-started/index.mdx
> +Account                       Foo Bar (Plan: All)
we can come up with something better than foo bar here IMO :)

2024-12-10 05:57 UTC, russorat commented on docs/getting-started/index.mdx
> +Account                       Foo Bar (Plan: All)
and the plan should be Free

2024-12-10 06:00 UTC, russorat commented on docs/getting-started/index.mdx
> +      - ""conn.ts.start < timestamp('2999-12-31T23:59:59Z')""
this expression doesn't make much sense. can we use something someone might actually use here as an example?

2024-12-10 06:01 UTC, russorat commented on docs/getting-started/index.mdx
> +<p className="text-xl">`on_http_request`</p>
this is a quickstart guide. IMO i'm not sure we need to explain all this stuff to them here. if the goal is to add oauth, let's just focus on that and skip this section IMO.

2024-12-10 06:03 UTC, russorat commented on docs/getting-started/index.mdx
> +Let's say you want to restrict access only to you and your coworkers by
I think the language here should be more focused. instead of "let's say", we should just say "We are going to restrict access to your endpoint"

2024-12-10 06:04 UTC, russorat commented on docs/getting-started/index.mdx
> +Create your first Traffic Policy rule by creating a new file called `auth.yaml`
do we need to use a policy file here? why not the command line flags? this is a quickstart after all.

2024-12-10 06:09 UTC, russorat commented on docs/getting-started/index.mdx
> +<div className="ngrok--cards ngrok--cards-flex ngrok--cards-row">
what about jwt?

2024-12-10 06:10 UTC, russorat commented on docs/getting-started/index.mdx
> +<div className="ngrok--cards ngrok--cards-flex ngrok--cards-row">
i'm not sure i'd consider this an "authentication method"

2024-12-10 06:11 UTC, russorat commented on docs/getting-started/index.mdx
> +ngrok supports many forms of authentication:
I think if you changed this to be something more generic like "ways to protect access to your endpoint, then you can get away with ip restrictions and webhook verification.

2024-12-10 06:13 UTC, russorat commented on docs/getting-started/index.mdx
> +  <TabItem value="docker" label="Docker">
it's not clear to me why docker is under the "run persistly" section.

2024-12-10 06:14 UTC, russorat commented on docs/getting-started/index.mdx
> +  <TabItem value="detach" label="Tmux/Screen/Zellij">
this doesn't actually tell you how to run persistently on any of these systems. how do you detach it?

2024-12-10 06:17 UTC, russorat requested changes
i think this needs a lot more work before we merge.

2025-03-06 14:25 UTC, S3Prototype commented
Closing for now; can re-open if necessary

2025-03-06 14:25 UTC, closed without merging