Fix security section for Hubspot and GitLab
ngrok/ngrok-docs pull request #288
Opened 2023-04-08 22:43 UTC by faonbr

2023-04-10 16:41 UTC, nijikokun requested changes

2023-04-10 16:41 UTC, nijikokun commented on docs/integrations/hubspot/webhooks.md
> +The ngrok signature webhook verification feature allows ngrok to assert that requests from your Frame.io webhook are the only traffic allowed to make calls to your localhost app.
Should be HubSpot

2023-04-20 05:43 UTC, russorat commented on docs/integrations/gitlab/webhooks.md
> +The ngrok signature webhook verification feature allows ngrok to assert that requests from your Frame.io webhook are the only traffic allowed to make calls to your localhost app.
```suggestion
The ngrok signature webhook verification feature allows ngrok to assert that requests from your Gitlab webhooks are the only traffic allowed to make calls to your localhost app.
```

2023-04-20 05:44 UTC, russorat commented on docs/integrations/hubspot/webhooks.md
> +The ngrok signature webhook verification feature allows ngrok to assert that requests from your Hubspot webhook are the only traffic allowed to make calls to your localhost app.
```suggestion
The ngrok signature webhook verification feature allows ngrok to assert that requests from your HubSpot webhook are the only traffic allowed to make calls to your localhost app.
```

2023-04-20 05:44 UTC, russorat approved these changes
lgtm

2023-04-20 05:45 UTC, merged