Adding 3.8 version support json policy file
ngrok/ngrok-docs pull request #641
Opened 2024-03-14 18:46 UTC by Abdiramen

2024-03-14 19:05 UTC, bobzilladev commented on docs/agent/version-support-policy.mdx
> +| Active         | 3.8x    | 2024-03-14   | 3.7.0  | 2025-03-14     | 2025-05-14  |
Latest to 3.8.0

2024-03-14 19:17 UTC, Abdiramen commented on docs/agent/version-support-policy.mdx
> +| Active         | 3.8x    | 2024-03-14   | 3.7.0  | 2025-03-14     | 2025-05-14  |
ope, thanks!

2024-03-14 19:35 UTC, salilsub requested changes
With the "what's new", can we just list which version is being released and a link to the chagelog?

2024-03-21 14:36 UTC, bobzilladev commented
@Abdiramen Looks like a change is requested for this changelog PR, and it needs to be deconflicted.

2024-03-21 14:52 UTC, Abdiramen commented
> With the "what's new", can we just list which version is being released and a link to the chagelog?

fixed here: https://github.com/ngrok/ngrok-docs/pull/641/commits/1b5f4903fdb2b98d4ceb69a1484ef47fc96767b4

2024-03-21 15:00 UTC, bobzilladev approved these changes

2024-03-21 15:20 UTC, merged