Updating FastAPI Docs with a python-ngrok example
ngrok/ngrok-docs pull request #775
Opened 2024-06-06 12:30 UTC by firecube-oss

* This PR adds an example of how to use Ngrok with the ngrok-python SDK

2024-07-02 00:41 UTC, nijikokun commented on docs/using-ngrok-with/fastAPI.md
> +   )
```suggestion
    )
```

2024-07-10 15:42 UTC, salilsub commented on docs/using-ngrok-with/fastAPI.md
> +# Option 1: Using ngrok-python
```suggestion
# Using ngrok with FastAPI
```

2024-07-10 15:44 UTC, salilsub commented on docs/using-ngrok-with/fastAPI.md
> +If you're looking to natively embed the ngrok agent into your FastAPI application, you can leverage the [pyngrok project](https://pyngrok.readthedocs.io/en/latest/integrations.html#fastapi) to start
```suggestion
```

2024-07-10 15:45 UTC, salilsub commented on docs/using-ngrok-with/fastAPI.md
> +You can leverage the [ngork-python](https://github.com/ngrok/ngrok-python) library to embed the ngrok agent in to FastAPI Applications.
```suggestion
You can leverage the [ngrok-python](https://github.com/ngrok/ngrok-python) library to embed the ngrok agent in to FastAPI Applications. 
```

2024-07-10 15:45 UTC, salilsub commented on docs/using-ngrok-with/fastAPI.md
> +  ngork-python, Pydantic and FastAPI libraries used in this example are sensitive to versions.  Use of Virtual Environments is highly recommended
```suggestion
  ngrok-python, Pydantic and FastAPI libraries used in this example are sensitive to versions.  Use of Virtual Environments is highly recommended 
```

2024-07-10 15:47 UTC, salilsub requested changes
Using `pyngrok` shouldn't be an option 2 since it isn't supported by ngrok. Using the SDK is the way to go, it should be the only option recommended in docs. If the suggested changes are made, will approve and merge.

2024-07-31 17:17 UTC, russorat approved these changes
lgtm! thank you!

2024-07-31 17:18 UTC, merged